services:
  db:
    image: pgvector/pgvector:pg17-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marcopolo
    ports:
      - "5432:5432"
    volumes:
      - pgdata_marcopolo:/var/lib/postgresql/data

volumes:
  pgdata_marcopolo:
